// Standart YHQ (O'zbekiston) — 42 mavzu.
// Lotinda saqlanadi: ilova standarti (Kiril rejimida avtomat kirillga o'giriladi).
// Ham "Mavzular bo'yicha" ekrani, ham savol qo'shish formasidagi dropdown shu ro'yxatni ishlatadi.
export const STANDARD_TOPICS: string[] = [
  'Umumiy qoidalar',
  'Haydovchilarning umumiy vazifalari',
  'Piyodalarning umumiy vazifalari',
  'Maxsus transport vositalarining imtiyozlari',
  'Ogohlantiruvchi belgilar',
  'Imtiyoz belgilari',
  'Taqiqlovchi belgilar',
  'Buyuruvchi belgilar',
  'Axborot-ko‘rsatgich belgilari',
  'Servis belgilari',
  'Qo‘shimcha axborot belgilari',
  'Yotiq chiziqlar',
  'Tik chiziqlar',
  'Svetofor ishoralari',
  'Tartibga soluvchining ishoralari',
  'Ogohlantiruvchi va avariya (xavf-xatar) ishoralari',
  'Harakatlanishni boshlash, manyovr qilish',
  'Yo‘lning qatnov qismida transport vositalarining joylashuvi',
  'Harakatlanish tezligi',
  'Quvib o‘tish',
  'To‘xtash va to‘xtab turish',
  'Chorrahalarda harakatlanish',
  'Tartibga solingan chorrahalar',
  'Tartibga solinmagan chorrahalar asosiy yo‘l yo‘nalishi to‘g‘riga',
  'Tartibga solinmagan chorrahalar teng ahamiyatli',
  'Tartibga solinmagan chorrahalar asosiy yo‘l yo‘nalishi o‘zgarishi',
  'Piyodalarning o‘tish joylari va yo‘nalishli transport bekatlari',
  'Temir yo‘l kesishmalari orqali harakatlanish',
  'Avtomagistrallarda harakatlanish',
  'Turar joy dahalarida harakatlanish',
  'Tik balandlik va nishabliklarda harakatlanish',
  'Yo‘nalishli transport vositalarining imtiyozlari',
  'Tashqi yoritish asboblaridan foydalanish',
  'Mexanik transport vositalarini shatakka olish',
  'Transport vositalarini boshqarishni o‘rgatish',
  'Odam tashish',
  'Yuk tashish',
  'Velosiped, moped va aravalar harakatlanishiga qo‘yiladigan talablar',
  'Mansabdor shaxslarning va fuqarolarning yo‘l harakati xavfsizligi bo‘yicha vazifalari',
  'Transport vositalaridan foydalanishni taqiqlash',
  'Harakat xavfsizligi asoslari',
  'Birinchi tibbiy yordam',
];
